# Form implementation generated from reading ui file 'list_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ListDialog(object):
    def setupUi(self, ListDialog):
        ListDialog.setObjectName("ListDialog")
        ListDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        ListDialog.resize(578, 441)
        ListDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ListDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.songs_list = QtWidgets.QListWidget(parent=ListDialog)
        self.songs_list.setObjectName("songs_list")
        self.verticalLayout.addWidget(self.songs_list)
        self.button_box = QtWidgets.QDialogButtonBox(parent=ListDialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(ListDialog)
        QtCore.QMetaObject.connectSlotsByName(ListDialog)

    def retranslateUi(self, ListDialog):
        _translate = QtCore.QCoreApplication.translate
        ListDialog.setWindowTitle(_translate("ListDialog", "Choose a song"))
