# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TableWindow(object):
    def setupUi(self, TableWindow):
        TableWindow.setObjectName("TableWindow")
        TableWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=TableWindow)
        self.centralwidget.setObjectName("centralwidget")
        TableWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=TableWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        TableWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=TableWindow)
        self.statusbar.setObjectName("statusbar")
        TableWindow.setStatusBar(self.statusbar)
        self.action_new = QtGui.QAction(parent=TableWindow)
        self.action_new.setObjectName("action_new")
        self.actionHi = QtGui.QAction(parent=TableWindow)
        self.actionHi.setObjectName("actionHi")
        self.action_save_all = QtGui.QAction(parent=TableWindow)
        self.action_save_all.setObjectName("action_save_all")
        self.action_autofill_ta = QtGui.QAction(parent=TableWindow)
        self.action_autofill_ta.setObjectName("action_autofill_ta")
        self.action_open = QtGui.QAction(parent=TableWindow)
        self.action_open.setObjectName("action_open")
        self.menuFile.addAction(self.action_new)
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_save_all)
        self.menuEdit.addAction(self.action_autofill_ta)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(TableWindow)
        QtCore.QMetaObject.connectSlotsByName(TableWindow)

    def retranslateUi(self, TableWindow):
        _translate = QtCore.QCoreApplication.translate
        TableWindow.setWindowTitle(_translate("TableWindow", "Ted: Songs"))
        self.menuFile.setTitle(_translate("TableWindow", "File"))
        self.menuEdit.setTitle(_translate("TableWindow", "Edit"))
        self.action_new.setText(_translate("TableWindow", "New Album"))
        self.action_new.setShortcut(_translate("TableWindow", "Ctrl+N"))
        self.actionHi.setText(_translate("TableWindow", "Hi"))
        self.action_save_all.setText(_translate("TableWindow", "Save All"))
        self.action_save_all.setShortcut(_translate("TableWindow", "Ctrl+Shift+S"))
        self.action_autofill_ta.setText(_translate("TableWindow", "Autofill Title and Artist based on file names"))
        self.action_open.setText(_translate("TableWindow", "Open"))
        self.action_open.setShortcut(_translate("TableWindow", "Ctrl+O"))
